name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  master:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Main Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}
  sotd:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: JavaScript or TypeScript snippet of the day
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.code.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          plugin_code: yes
          plugin_code_languages: javascript, typescript
          plugin_code_load: 400
  pagespeed:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Detailed report
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.pagespeed.detailed.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.GTOKEN }}
          plugin_pagespeed_url: https://plugins.itoncek.cf
  isocalendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
  langs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
  stargazers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Using chartist charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.stargazers.chartist.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist
  diffs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Repositories and diff history
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.lines.history.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 2
          plugin_lines_history_limit: 1
  licenses:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Licenses with open-source ratio graphs
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.licenses.ratio.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          template: repository
          repo: metrics
          plugin_licenses: yes
          plugin_licenses_legal: yes
          plugin_licenses_ratio: yes
  achivements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Detailed display
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          plugin_achievements: yes
